# Generated by Django 4.1.7 on 2023-03-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('public_key', models.CharField(default='', max_length=42)),
                ('private_key', models.CharField(default='', max_length=66)),
                ('chain', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
