# Generated by Django 4.1.7 on 2023-03-28 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_account_public_key_account_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='index',
            new_name='account_index',
        ),
    ]
